apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: ds
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
      name: pod
    - name: exporter
      port: 9000
      targetPort: 9000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deploy
  namespace: ds
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api-container
          image: lorenzo071/api_serv:1.0
          ports:
            - containerPort: 5002
            - containerPort: 9000
          env:
            - name: DB_SERV_NAME
              value: 'apidb'
            - name: MYSQL_DATABASE
              value: 'apidb'
            - name: MYSQL_USER
              value: 'root'
            - name: MYSQL_PASSWORD
              value: '12345'
            - name: MYSQL_ROOT_PASSWORD
              value: '12345'
            - name: SECRET_KEY
              value: "mySecretKey"