apiVersion: v1
kind: Service #per esporre un set di pod come servizio di rete.
metadata:
  name: city-service
  namespace: ds
spec:
  selector: # Specifica che questo servizio indirizzerà il traffico verso i pod che hanno l'etichetta app: city.
    app: city
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
      name: pod
    - name: exporter
      port: 9000
      targetPort: 9000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: city-deploy
  namespace: ds
spec:
  replicas: 1 #numero di pod
  selector: #Specifica un insieme di etichette che il Deployment userà per identificare quali pod gestire
    matchLabels: #Specifica una singola etichetta, in questo caso, "app: city". Ciò significa che il Deployment gestirà i pod che hanno l'etichetta "app: city".
      app: city
  template: # definisce il modello per la creazione dei pod
    metadata: # Contiene le etichette per i pod creati, con l'etichetta "app: city
      labels:
        app: city
    spec:
      containers:
        - name: city-container
          image: lorenzo071/city_serv:1.0
          ports:
            - containerPort: 5001
            - containerPort: 9000
          env:
            - name: DB_SERV_NAME
              value: 'citydb'
            - name: MYSQL_DATABASE
              value: 'citydb'
            - name: MYSQL_USER
              value: 'root'
            - name: MYSQL_PASSWORD
              value: '12345'
            - name: MYSQL_ROOT_PASSWORD
              value: '12345'
            - name: SECRET_KEY
              value: "mySecretKey"