apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  namespace: ds
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"

spec:
  rules:
    - host: localhost
      http:
        paths:
          - pathType: ImplementationSpecific
            path: /auth(/|$)(.*)
            backend:
              service:
                name: auth-service
                port:
                  number: 5000

          - pathType: ImplementationSpecific
            path: /city_serv(/|$)(.*)
            backend:
              service:
                name: city-service
                port:
                  number: 5001

          - pathType: ImplementationSpecific
            path: /sla_manager(/|$)(.*)
            backend:
              service:
                name: sla-manager
                port:
                  number: 5050
