apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nfydb
  namespace: ds
spec:
  serviceName: "nfydb"
  replicas: 1
  selector:
    matchLabels:
      app: nfydb
  template:
    metadata:
      labels:
        app: nfydb
    spec:
      containers:
        - name: nfydb
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: '12345'
            - name: MYSQL_DATABASE
              value: 'nfydb'
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-volume-nfy
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-volume-nfy
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 100Mi

---

apiVersion: v1
kind: Service
metadata:
  name: nfydb
  namespace: ds
spec:
  selector:
    app: nfydb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306