apiVersion: apps/v1
kind: StatefulSet #Un StatefulSet è un oggetto di Kubernetes che gestisce l'applicazione di tipo stato, come database, che richiedono identità persistente e accesso stabile ai dischi.
metadata:
  name: authdb
  namespace: ds
spec:
  serviceName: "authdb"
  replicas: 1
  selector:
    matchLabels:
      app: authdb
  template:
    metadata:
      labels:
        app: authdb
    spec:
      containers:
        - name: authdb
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: '12345'
            - name: MYSQL_DATABASE
              value: 'authdb'
          ports:
            - containerPort: 3306 #porta a destra del comopose
          volumeMounts:
            - name: mysql-volume-auth
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-volume-auth
      spec:
        accessModes: [ "ReadWriteOnce" ] #Questo specifica le modalità di accesso per il PersistentVolumeClaim. In questo caso, è impostato su "ReadWriteOnce", il che significa che il volume può essere montato in lettura/scrittura da un singolo nodo
        resources:
          requests:
            storage: 100Mi

---

apiVersion: v1
kind: Service
metadata:
  name: authdb
  namespace: ds
spec:
  selector:
    app: authdb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306